### ISSUE TITLE
i merged shit and i don't know what it did but the jumpy cool

### ISSUE THREAD

**Issue by Luckyduck37** [Rasmodius-10101/HeavenTimeMassacre#7]
it gave me an error but the jump looks cool.
if you know what happened and can explain plz do

**Comment by proudmoontruther** [comment]
for right now, don't merge anything into the main branch. If you want to make something, be sure to create a new branch instead of working straight into the main branch. Just so that it's easier to look at the changes and you can submit a Pull Request (PR) which allows us to look things over. (ofc i do the same thing cause i still suck at coding lmao), but yeah i'll look at what you did.
